#pragma once
#include "CoreMinimal.h"
#include "ETresItemDefAccessory.generated.h"

UENUM(BlueprintType)
enum class ETresItemDefAccessory : uint8 {
    NOTHING,
    ITEM01 UMETA(DisplayName = "Laughter Pin"),
    ITEM02 UMETA(DisplayName = "Forest Clasp"),
    ITEM03 UMETA(DisplayName = "Ability Ring"),
    ITEM04 UMETA(DisplayName = "Ability Ring+"),
    ITEM05 UMETA(DisplayName = "Technician's Ring"),
    ITEM06 UMETA(DisplayName = "Technician's Ring+"),
    ITEM07 UMETA(DisplayName = "Skill Ring"),
    ITEM08 UMETA(DisplayName = "Skillful Ring"),
    ITEM09 UMETA(DisplayName = "Expert's Ring"),
    ITEM10 UMETA(DisplayName = "Master's Ring"),
    ITEM11 UMETA(DisplayName = "Cosmic Ring"),
    ITEM12 UMETA(DisplayName = "Power Ring"),
    ITEM13 UMETA(DisplayName = "Buster Ring"),
    ITEM14 UMETA(DisplayName = "Valor Ring"),
    ITEM15 UMETA(DisplayName = "Phantom Ring"),
    ITEM16 UMETA(DisplayName = "Orichalcum Ring"),
    ITEM17 UMETA(DisplayName = "Magic Ring"),
    ITEM18 UMETA(DisplayName = "Rune Ring"),
    ITEM19 UMETA(DisplayName = "Force Ring"),
    ITEM20 UMETA(DisplayName = "Sorcerer's Ring"),
    ITEM21 UMETA(DisplayName = "Wisdom Ring"),
    ITEM22 UMETA(DisplayName = "Bronze Necklace"),
    ITEM23 UMETA(DisplayName = "Silver Necklace"),
    ITEM24 UMETA(DisplayName = "Master's Necklace"),
    ITEM25 UMETA(DisplayName = "Bronze Amulet"),
    ITEM26 UMETA(DisplayName = "Silver Amulet"),
    ITEM27 UMETA(DisplayName = "Gold Amulet"),
    ITEM28 UMETA(DisplayName = "Junior Medal"),
    ITEM29 UMETA(DisplayName = "Master Medal"),
    ITEM30 UMETA(DisplayName = "Star Medal"),
    ITEM31 UMETA(DisplayName = "Mickey Clasp"),
    ITEM32 UMETA(DisplayName = "Soldier's Earring"),
    ITEM33 UMETA(DisplayName = "Fencer's Earring"),
    ITEM34 UMETA(DisplayName = "Mage's Earring"),
    ITEM35 UMETA(DisplayName = "Slayer's Earring"),
    ITEM36 UMETA(DisplayName = "Moon Amulet"),
    ITEM37 UMETA(DisplayName = "Star Charm"),
    ITEM38 UMETA(DisplayName = "Cosmic Arts"),
    ITEM39 UMETA(DisplayName = "Crystal Regalia"),
    ITEM40 UMETA(DisplayName = "Water Cufflink"),
    ITEM41 UMETA(DisplayName = "Thunder Cufflink"),
    ITEM42 UMETA(DisplayName = "Fire Cufflink"),
    ITEM43 UMETA(DisplayName = "Aero Cufflink"),
    ITEM44 UMETA(DisplayName = "Blizzard Cufflink"),
    ITEM45 UMETA(DisplayName = "Celestriad"),
    ITEM46 UMETA(DisplayName = "Yin-Yang Cufflink"),
    ITEM47 UMETA(DisplayName = "Gourmand's Ring"),
    ITEM48 UMETA(DisplayName = "Draw Ring"),
    ITEM49 UMETA(DisplayName = "Lucky Ring"),
    ITEM50 UMETA(DisplayName = "Flanniversary Badge"),
    ITEM51,
    ITEM52,
    ITEM53,
    ITEM54,
    ITEM55,
    ITEM56,
    ITEM57,
    ITEM58,
    ITEM59,
    ITEM60,
    ITEM61,
    ITEM62,
    ITEM63,
    ITEM64,
    ITEM65,
    ITEM66,
    ITEM67,
    ITEM68,
    ITEM69,
    ITEM70,
    ITEM71,
    ITEM72,
    ITEM73,
    ITEM74,
    ITEM75,
    ITEM76,
    ITEM77,
    ITEM78,
    ITEM79,
    ITEM80,
    ITEM81,
    ITEM82,
    ITEM83,
    ITEM84,
    ITEM85,
    ITEM86,
    ITEM87,
    ITEM88,
    ITEM89,
    ITEM90,
    ITEM91,
    ITEM92,
    ITEM93,
    ITEM94,
    ITEM95,
    ITEM96,
    ITEM97,
    ITEM98,
    ITEM99,
    ITEM100,
    ITEM101,
    ITEM102,
    ITEM103,
    ITEM104,
    ITEM105,
    ITEM106,
    ITEM107,
    ITEM108,
    ITEM109,
    ITEM110,
    ITEM111 UMETA(DisplayName = "Breakthrough"),
    ITEM112 UMETA(DisplayName = "Crystal Regalia+"),
    _MAX = 0xC8,
};

