#pragma once
#include "CoreMinimal.h"
#include "ETresDlcChallengeRecordID.generated.h"

UENUM(BlueprintType)
enum class ETresDlcChallengeRecordID : uint8 {
    REC0101 UMETA(DisplayName = "Rock Titan"),
    REC0201 UMETA(DisplayName = "Titan Trio 1"),
    REC0202 UMETA(DisplayName = "Titan Trio 2"),
    REC0301 UMETA(DisplayName = "Demon Tide 0"),
    REC0401 UMETA(DisplayName = "Angelic Amber"),
    REC0501 UMETA(DisplayName = "King of Toys"),
    REC0601 UMETA(DisplayName = "Chaos Carriage"),
    REC0701 UMETA(DisplayName = "Grim Guardianess"),
    REC0801 UMETA(DisplayName = "Lump of Horror"),
    REC0901 UMETA(DisplayName = "Marshmallow"),
    REC1001 UMETA(DisplayName = "Skoll"),
    REC1101 UMETA(DisplayName = "Lightning Angler"),
    REC1201 UMETA(DisplayName = "Davy Jones"),
    REC1301 UMETA(DisplayName = "Darkubes"),
    REC1401 UMETA(DisplayName = "Dark Baymax 1"),
    REC1402 UMETA(DisplayName = "Dark Baymax 2"),
    REC1501 UMETA(DisplayName = "Demon Tide 1"),
    REC1502 UMETA(DisplayName = "Demon Tide 2"),
    REC1601 UMETA(DisplayName = "Nort Court 1"),
    REC1602 UMETA(DisplayName = "Nort Court 2"),
    REC1603 UMETA(DisplayName = "Nort Court 3"),
    REC1701 UMETA(DisplayName = "Dark Inferno"),
    REC1801 UMETA(DisplayName = "Armored Xehanort 1"),
    REC1802 UMETA(DisplayName = "Armored Xehanort 2"),
    REC1803 UMETA(DisplayName = "Armored Xehanort 3"),
    REC1901 UMETA(DisplayName = "Master Xehanort 1"),
    REC1902 UMETA(DisplayName = "Master Xehanort 2"),
    REC2001 UMETA(DisplayName = "RM Armored Xehanort 1"),
    REC2002 UMETA(DisplayName = "RM Armored Xehanort 2"),
    REC2101 UMETA(DisplayName = "LC Master Xehanort"),
    REC2201 UMETA(DisplayName = "LC Ansem"),
    REC2301 UMETA(DisplayName = "LC Xemnas"),
    REC2401 UMETA(DisplayName = "LC Xigbar"),
    REC2501 UMETA(DisplayName = "LC Luxord"),
    REC2601 UMETA(DisplayName = "LC Larxene"),
    REC2701 UMETA(DisplayName = "LC Marluxia"),
    REC2801 UMETA(DisplayName = "LC Saix"),
    REC2901 UMETA(DisplayName = "LC Terra-Xehanort"),
    REC3001 UMETA(DisplayName = "LC Dark Riku"),
    REC3101 UMETA(DisplayName = "LC Vanitas"),
    REC3201 UMETA(DisplayName = "LC Young Xehanort"),
    REC3301 UMETA(DisplayName = "LC Xion"),
    REC3401 UMETA(DisplayName = "Yozora"),
    ScoreCheckMax,
    _Max = 0x64,
};

