#pragma once
#include "CoreMinimal.h"
#include "ETresItemDefFoodstuff.generated.h"

UENUM(BlueprintType)
enum class ETresItemDefFoodstuff : uint8 {
    NOTHING,
    ITEM01 UMETA(DisplayName = "Crab"),
    ITEM02 UMETA(DisplayName = "Scallop"),
    ITEM03 UMETA(DisplayName = "Lobster"),
    ITEM04 UMETA(DisplayName = "Sole"),
    ITEM05 UMETA(DisplayName = "Eel"),
    ITEM06 UMETA(DisplayName = "Sea Bass"),
    ITEM07 UMETA(DisplayName = "Mussel"),
    ITEM08 UMETA(DisplayName = "Cod"),
    ITEM09 UMETA(DisplayName = "Pumpkin"),
    ITEM10 UMETA(DisplayName = "Zucchini"),
    ITEM11 UMETA(DisplayName = "Onion"),
    ITEM12 UMETA(DisplayName = "Tomato"),
    ITEM13 UMETA(DisplayName = "Eggplant"),
    ITEM14 UMETA(DisplayName = "Carrot"),
    ITEM15 UMETA(DisplayName = "Garlic"),
    ITEM16 UMETA(DisplayName = "Celery"),
    ITEM17 UMETA(DisplayName = "Morel"),
    ITEM18 UMETA(DisplayName = "Porcini"),
    ITEM19 UMETA(DisplayName = "Chanterelle"),
    ITEM20 UMETA(DisplayName = "Portobello"),
    ITEM21 UMETA(DisplayName = "Black Truffle"),
    ITEM22 UMETA(DisplayName = "King Oyster Mushroom"),
    ITEM23 UMETA(DisplayName = "Black Trumpet"),
    ITEM24 UMETA(DisplayName = "Miller Mushroom"),
    ITEM25 UMETA(DisplayName = "Cloves"),
    ITEM26 UMETA(DisplayName = "Rosemary"),
    ITEM27 UMETA(DisplayName = "Thyme"),
    ITEM28 UMETA(DisplayName = "Bay Leaf"),
    ITEM29 UMETA(DisplayName = "Basil"),
    ITEM30 UMETA(DisplayName = "Dill"),
    ITEM31 UMETA(DisplayName = "Parsley"),
    ITEM32 UMETA(DisplayName = "Saffron"),
    ITEM33 UMETA(DisplayName = "Apricot"),
    ITEM34 UMETA(DisplayName = "Gooseberry"),
    ITEM35 UMETA(DisplayName = "Lemon"),
    ITEM36 UMETA(DisplayName = "Orange"),
    ITEM37 UMETA(DisplayName = "Raspberry"),
    ITEM38 UMETA(DisplayName = "Pear"),
    ITEM39 UMETA(DisplayName = "Blackberry"),
    ITEM40 UMETA(DisplayName = "Apple"),
    ITEM41 UMETA(DisplayName = "Cheese"),
    ITEM42 UMETA(DisplayName = "Chocolate"),
    ITEM43 UMETA(DisplayName = "Caviar"),
    ITEM44 UMETA(DisplayName = "Butter"),
    ITEM45 UMETA(DisplayName = "Olive Oil"),
    ITEM46 UMETA(DisplayName = "Cornichon"),
    ITEM47 UMETA(DisplayName = "Rice"),
    ITEM48 UMETA(DisplayName = "Honey"),
    ITEM49 UMETA(DisplayName = "Sour Cherry"),
    ITEM50 UMETA(DisplayName = "Strawberry"),
    ITEM51 UMETA(DisplayName = "Blood Orange"),
    ITEM52 UMETA(DisplayName = "Banana"),
    ITEM53 UMETA(DisplayName = "Grapes"),
    ITEM54 UMETA(DisplayName = "Melon"),
    ITEM55 UMETA(DisplayName = "Watermelon"),
    ITEM56 UMETA(DisplayName = "Veal"),
    ITEM57 UMETA(DisplayName = "Beef"),
    ITEM58 UMETA(DisplayName = "Quail"),
    ITEM59 UMETA(DisplayName = "Filet Mignon"),
    _MAX = 0x40,
};

