#pragma once
#include "CoreMinimal.h"
#include "ETresItemDefNavimap.generated.h"

UENUM(BlueprintType)
enum class ETresItemDefNavimap : uint8 {
    NM_WCID_DW01,
    NM_WCID_DW02,
    NM_WCID_DW03,
    NM_WCID_DW04,
    NM_WCID_MI01 UMETA(DisplayName = "Map: Monsters, Inc."),
    NM_WCID_MI02 UMETA(DisplayName = "Map: The Factory"),
    NM_WCID_MI03,
    NM_WCID_MI04,
    NM_WCID_TS01 UMETA(DisplayName = "Map: Andy's House"),
    NM_WCID_TS02 UMETA(DisplayName = "Map: Galaxy Toys"),
    NM_WCID_TS03,
    NM_WCID_TS04,
    NM_WCID_FZ01 UMETA(DisplayName = "Map: The North Mountain"),
    NM_WCID_FZ02 UMETA(DisplayName = "Map: The Labyrinth of Ice"),
    NM_WCID_FZ03,
    NM_WCID_FZ04,
    NM_WCID_RA01 UMETA(DisplayName = "Map: The Forest (1/2)"),
    NM_WCID_RA02 UMETA(DisplayName = "Map: The Forest (2/2)"),
    NM_WCID_RA03,
    NM_WCID_RA04,
    NM_WCID_CA01 UMETA(DisplayName = "Map: Port Royal Waters"),
    NM_WCID_CA02 UMETA(DisplayName = "Map: Sandbar Isle"),
    NM_WCID_CA03 UMETA(DisplayName = "Map: Ship's End"),
    NM_WCID_CA04 UMETA(DisplayName = "Map: Isla de los Mástiles"),
    NM_WCID_HE01 UMETA(DisplayName = "Map: Realm of the Gods"),
    NM_WCID_HE02 UMETA(DisplayName = "Map: Mount Olympus"),
    NM_WCID_HE03 UMETA(DisplayName = "Map: Thebes"),
    NM_WCID_HE04,
    NM_WCID_BX01 UMETA(DisplayName = "Map: The City"),
    NM_WCID_BX02,
    NM_WCID_BX03,
    NM_WCID_BX04,
    NM_WCID_TT01 UMETA(DisplayName = "Map: The Neighborhood"),
    NM_WCID_TT02,
    NM_WCID_TT03,
    NM_WCID_TT04,
    NM_WCID_PO01,
    NM_WCID_PO02,
    NM_WCID_PO03,
    NM_WCID_PO04,
    NM_WCID_KG01 UMETA(DisplayName = "Map: The Badlands"),
    NM_WCID_KG02 UMETA(DisplayName = "Map: The Skein of Severance"),
    NM_WCID_KG03,
    NM_WCID_KG04,
    NM_WCID_EW01,
    NM_WCID_EW02,
    NM_WCID_EW03,
    NM_WCID_EW04,
    NM_WCID_BT01 UMETA(DisplayName = "Map: The Stairway to the Sky"),
    NM_WCID_BT02 UMETA(DisplayName = "Map: Breezy Quarter"),
    NM_WCID_BT03,
    NM_WCID_BT04,
    NM_WCID_CA05 UMETA(DisplayName = "Map: Huddled Isles"),
    _MAX = 0x64,
};

