#pragma once
#include "CoreMinimal.h"
#include "ETresItemDefMaterial.generated.h"

UENUM(BlueprintType)
enum class ETresItemDefMaterial : uint8 {
    NOTHING,
    ITEM01 UMETA(DisplayName = "Blazing Shard"),
    ITEM02 UMETA(DisplayName = "Blazing Stone"),
    ITEM03 UMETA(DisplayName = "Blazing Gem"),
    ITEM04 UMETA(DisplayName = "Blazing Crystal"),
    ITEM05 UMETA(DisplayName = "Frost Shard"),
    ITEM06 UMETA(DisplayName = "Frost Stone"),
    ITEM07 UMETA(DisplayName = "Frost Gem"),
    ITEM08 UMETA(DisplayName = "Frost Crystal"),
    ITEM09 UMETA(DisplayName = "Lightning Shard"),
    ITEM10 UMETA(DisplayName = "Lightning Stone"),
    ITEM11 UMETA(DisplayName = "Lightning Gem"),
    ITEM12 UMETA(DisplayName = "Lightning Crystal"),
    ITEM13 UMETA(DisplayName = "Lucid Shard"),
    ITEM14 UMETA(DisplayName = "Lucid Stone"),
    ITEM15 UMETA(DisplayName = "Lucid Gem"),
    ITEM16 UMETA(DisplayName = "Lucid Crystal"),
    ITEM17 UMETA(DisplayName = "Pulsing Shard"),
    ITEM18 UMETA(DisplayName = "Pulsing Stone"),
    ITEM19 UMETA(DisplayName = "Pulsing Gem"),
    ITEM20 UMETA(DisplayName = "Pulsing Crystal"),
    ITEM21 UMETA(DisplayName = "Writhing Shard"),
    ITEM22 UMETA(DisplayName = "Writhing Stone"),
    ITEM23 UMETA(DisplayName = "Writhing Gem"),
    ITEM24 UMETA(DisplayName = "Writhing Crystal"),
    ITEM25 UMETA(DisplayName = "Betwixt Shard"),
    ITEM26 UMETA(DisplayName = "Betwixt Stone"),
    ITEM27 UMETA(DisplayName = "Betwixt Gem"),
    ITEM28 UMETA(DisplayName = "Betwixt Crystal"),
    ITEM29 UMETA(DisplayName = "Twilight Shard"),
    ITEM30 UMETA(DisplayName = "Twilight Stone"),
    ITEM31 UMETA(DisplayName = "Twilight Gem"),
    ITEM32 UMETA(DisplayName = "Twilight Crystal"),
    ITEM33 UMETA(DisplayName = "Mythril Shard"),
    ITEM34 UMETA(DisplayName = "Mythril Stone"),
    ITEM35 UMETA(DisplayName = "Mythril Gem"),
    ITEM36 UMETA(DisplayName = "Mythril Crystal"),
    ITEM37 UMETA(DisplayName = "Sinister Shard"),
    ITEM38 UMETA(DisplayName = "Sinister Stone"),
    ITEM39 UMETA(DisplayName = "Sinister Gem"),
    ITEM40 UMETA(DisplayName = "Sinister Crystal"),
    ITEM41 UMETA(DisplayName = "Soothing Shard"),
    ITEM42 UMETA(DisplayName = "Soothing Stone"),
    ITEM43 UMETA(DisplayName = "Soothing Gem"),
    ITEM44 UMETA(DisplayName = "Soothing Crystal"),
    ITEM45 UMETA(DisplayName = "Wellspring Shard"),
    ITEM46 UMETA(DisplayName = "Wellspring Stone"),
    ITEM47 UMETA(DisplayName = "Wellspring Gem"),
    ITEM48 UMETA(DisplayName = "Wellspring Crystal"),
    ITEM49 UMETA(DisplayName = "Hungry Shard"),
    ITEM50 UMETA(DisplayName = "Hungry Stone"),
    ITEM51 UMETA(DisplayName = "Hungry Gem"),
    ITEM52 UMETA(DisplayName = "Hungry Crystal"),
    ITEM53 UMETA(DisplayName = "Fluorite"),
    ITEM54 UMETA(DisplayName = "Damascus"),
    ITEM55 UMETA(DisplayName = "Adamantite"),
    ITEM56 UMETA(DisplayName = "Orichalcum"),
    ITEM57 UMETA(DisplayName = "Orichalcum+"),
    ITEM58 UMETA(DisplayName = "Electrum"),
    ITEM59 UMETA(DisplayName = "Evanescent Crystal"),
    ITEM60 UMETA(DisplayName = "Illusory Crystal"),
    _MAX = 0x64,
};

