#pragma once
#include "CoreMinimal.h"
#include "ETresItemDefProtector.generated.h"

UENUM(BlueprintType)
enum class ETresItemDefProtector : uint8 {
    NOTHING,
    ITEM01 UMETA(DisplayName = "Hero's Belt"),
    ITEM02 UMETA(DisplayName = "Hero's Glove"),
    ITEM03 UMETA(DisplayName = "Shield Belt"),
    ITEM04 UMETA(DisplayName = "Defense Belt"),
    ITEM05 UMETA(DisplayName = "Guardian's Belt"),
    ITEM06 UMETA(DisplayName = "Power Band"),
    ITEM07 UMETA(DisplayName = "Buster Band"),
    ITEM08 UMETA(DisplayName = "Buster Band+"),
    ITEM09 UMETA(DisplayName = "Cosmic Belt"),
    ITEM10 UMETA(DisplayName = "Cosmic Belt+"),
    ITEM11 UMETA(DisplayName = "Fire Bangle"),
    ITEM12 UMETA(DisplayName = "Firaga Bangle"),
    ITEM13 UMETA(DisplayName = "Firaza Bangle"),
    ITEM14 UMETA(DisplayName = "Fire Chain"),
    ITEM15 UMETA(DisplayName = "Blizzard Choker"),
    ITEM16 UMETA(DisplayName = "Blizzara Choker"),
    ITEM17 UMETA(DisplayName = "Blizzaga Choker"),
    ITEM18 UMETA(DisplayName = "Blizzard Chain"),
    ITEM19 UMETA(DisplayName = "Thunder Trinket"),
    ITEM20 UMETA(DisplayName = "Thundaga Trinket"),
    ITEM21 UMETA(DisplayName = "Thundaza Trinket"),
    ITEM22 UMETA(DisplayName = "Thunder Chain"),
    ITEM23 UMETA(DisplayName = "Dark Anklet"),
    ITEM24 UMETA(DisplayName = "Midnight Anklet"),
    ITEM25 UMETA(DisplayName = "Chaos Anklet"),
    ITEM26 UMETA(DisplayName = "Dark Chain"),
    ITEM27 UMETA(DisplayName = "Divine Bandanna"),
    ITEM28 UMETA(DisplayName = "Elven Bandanna"),
    ITEM29 UMETA(DisplayName = "Aqua Chaplet"),
    ITEM30 UMETA(DisplayName = "Wind Fan"),
    ITEM31 UMETA(DisplayName = "Storm Fan"),
    ITEM32 UMETA(DisplayName = "Aero Armlet"),
    ITEM33 UMETA(DisplayName = "Aegis Chain"),
    ITEM34 UMETA(DisplayName = "Acrisius"),
    ITEM35 UMETA(DisplayName = "Cosmic Chain"),
    ITEM36 UMETA(DisplayName = "Petite Ribbon"),
    ITEM37 UMETA(DisplayName = "Ribbon"),
    ITEM38 UMETA(DisplayName = "Fira Bangle"),
    ITEM39 UMETA(DisplayName = "Blizzaza Choker"),
    ITEM40 UMETA(DisplayName = "Thundara Trinket"),
    ITEM41 UMETA(DisplayName = "Shadow Anklet"),
    ITEM42 UMETA(DisplayName = "Abas Chain"),
    ITEM43 UMETA(DisplayName = "Acrisius+"),
    ITEM44 UMETA(DisplayName = "Royal Ribbon"),
    ITEM45 UMETA(DisplayName = "Firefighter Rosette"),
    ITEM46 UMETA(DisplayName = "Umbrella Rosette"),
    ITEM47 UMETA(DisplayName = "Mask Rosette"),
    ITEM48 UMETA(DisplayName = "Snowman Rosette"),
    ITEM49 UMETA(DisplayName = "Insulator Rosette"),
    ITEM50 UMETA(DisplayName = "Power Weight"),
    ITEM51 UMETA(DisplayName = "Magic Weight"),
    ITEM52 UMETA(DisplayName = "Master Belt"),
    _MAX = 0x64,
};

