#pragma once
#include "CoreMinimal.h"
#include "ETresItemDefFood.generated.h"

UENUM(BlueprintType)
enum class ETresItemDefFood : uint8 {
    NOTHING,
    SOUP01 UMETA(DisplayName = "Pumpkin Velouté"),
    SOUP02 UMETA(DisplayName = "Consommé"),
    SOUP03 UMETA(DisplayName = "Carrot Potage"),
    SOUP04 UMETA(DisplayName = "Crab Bisque"),
    SOUP05 UMETA(DisplayName = "Cold Tomato Soup"),
    APPETIZER01 UMETA(DisplayName = "Scallop Poêlé"),
    APPETIZER02 UMETA(DisplayName = "Lobster Mousse"),
    APPETIZER03 UMETA(DisplayName = "Mushroom Terrine"),
    APPETIZER04 UMETA(DisplayName = "Ratatouille"),
    APPETIZER05 UMETA(DisplayName = "Caprese Salad"),
    FISHDISH01 UMETA(DisplayName = "Sole Meunière"),
    FISHDISH02 UMETA(DisplayName = "Eel Matelote"),
    FISHDISH03 UMETA(DisplayName = "Sea Bass en Papillote"),
    FISHDISH04 UMETA(DisplayName = "Bouillabaisse"),
    FISHDISH05 UMETA(DisplayName = "Seafood Tartare"),
    FISHDISH06 UMETA(DisplayName = "Sea Bass Poêlé"),
    MEETDISH01 UMETA(DisplayName = "Sweetbread Poêlé"),
    MEETDISH02 UMETA(DisplayName = "Beef Sauté"),
    MEETDISH03 UMETA(DisplayName = "Beef Bourguignon"),
    MEETDISH04 UMETA(DisplayName = "Stuffed Quail"),
    MEETDISH05 UMETA(DisplayName = "Filet Mignon Poêlé"),
    DESSERT01 UMETA(DisplayName = "Crêpes Suzette"),
    DESSERT02 UMETA(DisplayName = "Chocolate Mousse"),
    DESSERT03 UMETA(DisplayName = "Fresh Fruit Compote"),
    DESSERT04 UMETA(DisplayName = "Berries au Fromage"),
    DESSERT05 UMETA(DisplayName = "Warm Banana Soufflé"),
    DESSERT06 UMETA(DisplayName = "Fruit Gelée"),
    DESSERT07 UMETA(DisplayName = "Tarte aux Fruits"),
    SOUP01P UMETA(DisplayName = "Pumpkin Velouté+"),
	SOUP02P UMETA(DisplayName = "Consommé+"),
	SOUP03P UMETA(DisplayName = "Carrot Potage+"),
	SOUP04P UMETA(DisplayName = "Crab Bisque+"),
	SOUP05P UMETA(DisplayName = "Cold Tomato Soup+"),
	APPETIZER01P UMETA(DisplayName = "Scallop Poêlé+"),
	APPETIZER02P UMETA(DisplayName = "Lobster Mousse+"),
	APPETIZER03P UMETA(DisplayName = "Mushroom Terrine+"),
	APPETIZER04P UMETA(DisplayName = "Ratatouille+"),
	APPETIZER05P UMETA(DisplayName = "Caprese Salad+"),
	FISHDISH01P UMETA(DisplayName = "Sole Meunière+"),
	FISHDISH02P UMETA(DisplayName = "Eel Matelote+"),
	FISHDISH03P UMETA(DisplayName = "Sea Bass en Papillote+"),
	FISHDISH04P UMETA(DisplayName = "Bouillabaisse+"),
	FISHDISH05P UMETA(DisplayName = "Seafood Tartare+"),
	FISHDISH06P UMETA(DisplayName = "Sea Bass Poêlé+"),
	MEETDISH01P UMETA(DisplayName = "Sweetbread Poêlé+"),
	MEETDISH02P UMETA(DisplayName = "Beef Sauté+"),
	MEETDISH03P UMETA(DisplayName = "Beef Bourguignon+"),
	MEETDISH04P UMETA(DisplayName = "Stuffed Quail+"),
	MEETDISH05P UMETA(DisplayName = "Filet Mignon Poêlé+"),
	DESSERT01P UMETA(DisplayName = "Crêpes Suzette+"),
	DESSERT02P UMETA(DisplayName = "Chocolate Mousse+"),
	DESSERT03P UMETA(DisplayName = "Fresh Fruit Compote+"),
	DESSERT04P UMETA(DisplayName = "Berries au Fromage+"),
	DESSERT05P UMETA(DisplayName = "Warm Banana Soufflé+"),
	DESSERT06P UMETA(DisplayName = "Fruit Gelée+"),
	DESSERT07P UMETA(DisplayName = "Tarte aux Fruits+"),
    _MAX = 0x40,
};

