#pragma once
#include "CoreMinimal.h"
#include "ETresItemDefWeapon.generated.h"

UENUM(BlueprintType)
enum class ETresItemDefWeapon : uint8 {
    WEP_NOEQUIP,
    WEP_KEYBLADE00 UMETA(DisplayName = "Kingdom Key"),
    WEP_KEYBLADE02 UMETA(DisplayName = "Hero's Origin"),
    WEP_KEYBLADE01 UMETA(DisplayName = "Shooting Star"),
    WEP_KEYBLADE03 UMETA(DisplayName = "Favorite Deputy"),
    WEP_KEYBLADE04 UMETA(DisplayName = "Ever After"),
    WEP_KEYBLADE09 UMETA(DisplayName = "Happy Gear"),
    WEP_KEYBLADE06 UMETA(DisplayName = "Crystal Snow"),
    WEP_KEYBLADE07 UMETA(DisplayName = "Honey Spout"),
    WEP_KEYBLADE08 UMETA(DisplayName = "Nano Gear"),
    WEP_KEYBLADE05 UMETA(DisplayName = "Wheel of Fate"),
    WEP_KEYBLADE11 UMETA(DisplayName = "Grand Chef"),
    WEP_KEYBLADE10 UMETA(DisplayName = "Classic Tone"),
    WEP_KEYBLADE12 UMETA(DisplayName = "Oathkeeper"),
    WEP_KEYBLADE13 UMETA(DisplayName = "Oblivion"),
    WEP_KEYBLADE14 UMETA(DisplayName = "Ultima Weapon"),
    WEP_KEYBLADE15 UMETA(DisplayName = "Midnight Blue"),
    WEP_KEYBLADE16 UMETA(DisplayName = "Phantom Green"),
    WEP_KEYBLADE17 UMETA(DisplayName = "Starlight"),
    WEP_KEYBLADE18 UMETA(DisplayName = "Elemental Encoder"),
    WEP_KEYBLADE19 UMETA(DisplayName = "Sora Unused 19"),
    WEP_DONALD00 UMETA(DisplayName = "Mage's Staff"),
    WEP_DONALD01 UMETA(DisplayName = "Mage's Staff+"),
    WEP_DONALD02 UMETA(DisplayName = "Warhammer"),
    WEP_DONALD03 UMETA(DisplayName = "Warhammer+"),
    WEP_DONALD04 UMETA(DisplayName = "Magician's Wand"),
    WEP_DONALD05 UMETA(DisplayName = "Magician's Wand+"),
    WEP_DONALD06 UMETA(DisplayName = "Nirvana"),
    WEP_DONALD07 UMETA(DisplayName = "Nirvana+"),
    WEP_DONALD08 UMETA(DisplayName = "Astrolabe"),
    WEP_DONALD09 UMETA(DisplayName = "Astrolabe+"),
    WEP_DONALD10 UMETA(DisplayName = "Heartless Maul"),
    WEP_DONALD11 UMETA(DisplayName = "Heartless Maul+"),
    WEP_DONALD12 UMETA(DisplayName = "Save the Queen"),
    WEP_DONALD13 UMETA(DisplayName = "Save the Queen+"),
    WEP_DONALD14 UMETA(DisplayName = "Donald Unused 14"),
    WEP_DONALD15 UMETA(DisplayName = "Donald Unused 15"),
    WEP_DONALD16 UMETA(DisplayName = "Donald Unused 16"),
    WEP_DONALD17 UMETA(DisplayName = "Donald Unused 17"),
    WEP_DONALD18 UMETA(DisplayName = "Donald Unused 18"),
    WEP_DONALD19 UMETA(DisplayName = "Donald Unused 19"),
    WEP_GOOFY00 UMETA(DisplayName = "Knight's Shield"),
    WEP_GOOFY01 UMETA(DisplayName = "Knight's Shield+"),
    WEP_GOOFY02 UMETA(DisplayName = "Clockwork Shield"),
    WEP_GOOFY03 UMETA(DisplayName = "Clockwork Shield+"),
    WEP_GOOFY04 UMETA(DisplayName = "Star Shield"),
    WEP_GOOFY05 UMETA(DisplayName = "Star Shield+"),
    WEP_GOOFY06 UMETA(DisplayName = "Aegis Shield"),
    WEP_GOOFY07 UMETA(DisplayName = "Aegis Shield+"),
    WEP_GOOFY08 UMETA(DisplayName = "Storm Anchor"),
    WEP_GOOFY09 UMETA(DisplayName = "Storm Anchor+"),
    WEP_GOOFY10 UMETA(DisplayName = "Nobody Guard"),
    WEP_GOOFY11 UMETA(DisplayName = "Nobody Guard+"),
    WEP_GOOFY12 UMETA(DisplayName = "Save the King"),
    WEP_GOOFY13 UMETA(DisplayName = "Save the King+"),
    WEP_GOOFY14 UMETA(DisplayName = "Goofy Unused 14"),
	WEP_GOOFY15 UMETA(DisplayName = "Goofy Unused 15"),
	WEP_GOOFY16 UMETA(DisplayName = "Goofy Unused 16"),
	WEP_GOOFY17 UMETA(DisplayName = "Goofy Unused 17"),
	WEP_GOOFY18 UMETA(DisplayName = "Goofy Unused 18"),
	WEP_GOOFY19 UMETA(DisplayName = "Goofy Unused 19"),
    WEP_AQUA00 UMETA(DisplayName = "Aqua 00"),
    WEP_AQUA01 UMETA(DisplayName = "Aqua 01"),
    WEP_AQUA02 UMETA(DisplayName = "Aqua Unused 02"),
    WEP_AQUA03 UMETA(DisplayName = "Aqua Unused 03"),
    WEP_MICKEY00 UMETA(DisplayName = "Mickey Unused 00"),
    WEP_MICKEY01 UMETA(DisplayName = "Mickey 01"),
    WEP_MICKEY02 UMETA(DisplayName = "Mickey 02"),
    WEP_MICKEY03 UMETA(DisplayName = "Mickey Unused 03"),
    WEP_HERCULES00 UMETA(DisplayName = "Heart of a Hero"),
    WEP_WOODY00 UMETA(DisplayName = "Cowboy's Pride"),
    WEP_BUZZ00 UMETA(DisplayName = "Space Ranger Suit"),
    WEP_RAPUNZEL00 UMETA(DisplayName = "Golden Hair"),
    WEP_FLYNN00 UMETA(DisplayName = "Frying Pan"),
    WEP_JACK_SPARROW00 UMETA(DisplayName = "Skill & Crossbones"),
    WEP_MARSHMALLOW00 UMETA(DisplayName = "Ice Claws"),
    WEP_BAYMAX00 UMETA(DisplayName = "Powered Suit"),
    WEP_SULLEY00 UMETA(DisplayName = "Claws"),
    WEP_MIKE00 UMETA(DisplayName = "Knockout Body"),
    WEP_RIKU00 UMETA(DisplayName = "Riku 00"),
    WEP_RIKU01 UMETA(DisplayName = "Riku 01"),
    WEP_RIKU02 UMETA(DisplayName = "Riku Unused 02"),
    WEP_RIKU03 UMETA(DisplayName = "Riku Unused 03"),
    WEP_KAIRI00,
    WEP_LEA00,
    WEP_TERRA00,
    WEP_VENTUS00,
    WEP_ROXAS00,
    WEP_XION00,
    WEP_FRD_SORA00,
    _WEP_MAX = 0x64,
};

